version: '3'
services:
  django:
    build: ./app/
    command: >
      bash -c "python3 manage.py collectstatic --no-input -v 2 && 
      python3 manage.py makemigrations && python3 manage.py migrate 
      && python3 sqlite_to_postgres/load_data.py && uwsgi --ini uwsgi.ini"
    env_file:
      - app/.env
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    expose:
      - "8000"
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    image: postgres:15
    container_name: mov-admin-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    env_file:
      - app/.env
    ports:
      - '5432:5432'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static:/opt/app/static
      - media:/opt/app/media
    depends_on:
      - django
    ports:
      - "80:80"

volumes:
  pg_data:
  static:
  media: