version: '3.9'
services:
  django:
    container_name: django-example
    build: ./app
    command: >
      bash -c "uwsgi --ini uwsgi.ini"
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    image: postgres:15
    container_name: mov-admin-db
    volumes:
      - ~/.PythonProjects/docker_pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'